name: Deploy to EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show SSH Key
        run: |
          echo "${{ secrets.EC2_HOST }}"
          echo "${{ secrets.EC2_SSH_KEY }}"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/web/platform
            git pull origin production
            sudo chown -R ubuntu:ubuntu ~/web/platform/dist
            npm install
            npm run build
            sudo nginx -t && sudo systemctl reload nginx
